(source gnu)
(source melpa)

(depends-on "auto-complete")
(depends-on "cask")
(depends-on "expand-region")
(depends-on "helm")
(depends-on "magit")
(depends-on "migemo")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "yasnippet")