(source gnu)
(source melpa)

(depends-on "auto-complete")
(depends-on "cask")
(depends-on "e2wm")
(depends-on "expand-region")
(depends-on "helm")
(depends-on "helm-ls-git")
(depends-on "magit")
(depends-on "migemo")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "php-mode")
(depends-on "popwin")
(depends-on "web-mode")
(depends-on "yasnippet")